stages:
  creation-dataset:
    cmd: python scripts/create_dataset.py
    deps:
    - scripts/create_dataset.py
    outs:
    - assets/data
  extract-feature:
    cmd: python scripts/extract_features.py
    deps:
    - assets/data/test.csv
    - assets/data/train.csv
    - scripts/extract_features.py
    outs:
    - assets/features
  train-model:
    cmd: python scripts/train_model.py
    deps:
    - assets/features/train_features.csv
    - assets/features/train_labels.csv
    - scripts/train_model.py
    outs:
    - assets/models
